# Generated by Django 3.2.7 on 2021-09-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='demo/%Y/%m/%d'),
        ),
    ]
