# Generated by Django 3.2.7 on 2021-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_demo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/demo/%Y/%m/%d'),
        ),
    ]
