# Generated by Django 3.2.7 on 2021-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_demo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='task',
            field=models.CharField(choices=[('Segmentation', 'Segmentation'), ('Object Detection', 'Object Detection'), ('Keypoint Detection', 'Keypoint Detection'), ('Classification', 'Classification'), ('GAN', 'GAN')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
