# Generated by Django 3.2.7 on 2021-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_demo_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='url',
            field=models.URLField(default=1, verbose_name='Site URL'),
            preserve_default=False,
        ),
    ]
