# Generated by Django 3.2.7 on 2021-10-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_demo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='photo',
        ),
    ]
